version: '2'
services:
  ui:
    image: abr/ui
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ${PHOTOS_VOLUME}:/photos
    networks:
      - api

  api:
    image: abr/api
    depends_on:
      - db
    volumes:
      - ${PHOTOS_VOLUME}:/srv/photos
    networks:
      - api
      - db

  db:
    image: postgres:9.5.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abr
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    networks:
      - db

networks:
  api:
  db:
