version: '2'
services:
  ui:
    image: abr/ui
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - api

  api:
    image: abr/api
    depends_on:
      - db
    networks:
      - api
      - db

  db:
    image: postgres:9.5.4
    networks:
      - db

networks:
  api:
  db:
