server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

logging:
  pattern:
    level: ip:%X{ip} %5p
  level:
    root: WARN
    bzh:
      abr: DEBUG
    org:
      hibernate:
        SQL: DEBUG

jwt:
  cookie: Authorization
  secret: ArchersDeLaBretagneRomantique!
  expiration: 43200000

photos:
  path: photos/
