server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/abr
    username: postgres
    password: postgres

logging:
  pattern:
    level: ip:%X{ip} %5p
  level:
    root: WARN
    bzh:
      abr: DEBUG

jwt:
  cookie: Authorization
  secret: ArchersDeLaBretagneRomantique!
  expiration: 43200000

photos:
  path: photos/
