server:
  port: 8080

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/abr
    username: postgres
    password: postgres

logging:
  level:
    root: WARN
    bzh:
      abr: DEBUG