server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/abr
    username: postgres
    password: postgres

logging:
  level:
    root: ERROR

jwt:
  cookie: Authorization
  secret: cinquiemeDeCouv'key
  expiration: 43200000