server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://db:5432/abr
    username: postgres
    password: postgres

logging:
  pattern:
    level: ip:%X{ip} %5p
  level:
    root: ERROR

jwt:
  cookie: Authorization
  secret: ArchersDeLaBretagneRomantique!
  expiration: 43200000

photos:
  path: /photos/
